version: "3.8"

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - /home/usuario/Documentos/backend-PA/backend-PA:/app

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
