openapi: 3.0.0
info:
  title: Backend-PA
  description: documentation of api
  version: 1.0.0

paths:
  /users:
    get:
      summary: Retorna todos os usuários
      responses:
        "200":
          description: OK
  /gastos:
    get:
      summary: Retorna todos os gastos
      responses:
        "200":
          description: OK
